require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EndOfLine:
  Enabled: false
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/SaveBang:
  Enabled: true

Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/WordArray:
  Enabled: false
